services:
  wdb:
    image: postgres:latest
    container_name: wdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waterloops
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    container_name: backend
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: jdbc:postgresql://wdb:5432/waterloops
