spring:
  application:
    name: waterloop
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/waterloops}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
